Appointment/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^login/', auth_views.login, {'template_name': 'appointment/login.html'}, name='login'),
    url(r'^logout/', auth_views.logout, name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'^appointment/', include('appointment.urls')),
    url(r'^api/', include('api.urls')),
]

api/urls.py
from django.conf.urls import url
from api.views import EventList, EventDateList, EventTimeList


urlpatterns = [
    url(r'^v1/(?P<eventdate_id>[0-9a-zA-Z_-]+)/eventtime/$', EventTimeList.as_view(), name='api-event-time-list'),
    url(r'^v1/(?P<event_id>[0-9a-zA-Z_-]+)/eventdate/$', EventDateList.as_view(), name='api-event-date-list'),
    url(r'^v1/events/$', EventList.as_view(), name='api-event-list'),
]

appointment/urls.py
from django.conf.urls import url
from appointment import views

urlpatterns = [
    url(r'^list/$', views.appointent_list, name='event-list'),
    url(r'^(?P<id>[0-9]+)/$', views.appointment_detail, name='event-detail'),
    url(r'^get_event_time/(?P<id>[0-9]+)/$', views.get_event_time, name='get-event-time'),
    url(r'^get_event_part/(?P<id>[0-9]+)/$', views.get_event_part, name='get-event-part'),
    url(r'^addEvent/$', views.add_event, name='event-add'),
    url(r'^saveEvent/$', views.save_event, name='event-save'),
    url(r'^addDayEvent/(?P<id>[0-9]+)/$', views.event_add_day, name='event-add-day'),
    url(r'^saveDayEvent/(?P<id>[0-9]+)/$', views.event_save_day, name='event-save-day'),
    url(r'^addParticipant/(?P<id>[0-9]+)/$', views.add_participant, name='add-participant'),
]

appointment/models.py
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models


SHORT_TEXT_LEN = 100

class Event(models.Model):
    title = models.CharField(verbose_name="Title", max_length=200)
    description = models.TextField(verbose_name='Description')
    starter = models.ForeignKey(User, verbose_name="Event Author")

    def __str__(self):
        return self.title

    def get_cut(self):
        if self.description > SHORT_TEXT_LEN:
            return self.description[:SHORT_TEXT_LEN]
        return self.description

class EventDate(models.Model):
    eventDate = models.DateField(verbose_name="Event Date")
    event = models.ForeignKey(Event, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.eventDate.strftime('%d %B %Y'))

class EventTime(models.Model):
    eventTimeStart = models.TimeField(verbose_name='Event Start Time')
    eventTimeFinish = models.TimeField(verbose_name='Event Finish Time')
    eventDate = models.ForeignKey(EventDate, verbose_name="Event Date", on_delete=models.CASCADE)

    def __str__(self):
        return "{} - {}".format(self.eventTimeStart.strftime('%M:%H'), self.eventTimeFinish.strftime('%M:%H'))

class Participants (models.Model):
    name = models.CharField(verbose_name='Full Name', max_length=200)
    email = models.EmailField(verbose_name='Email', max_length=100)
    eventTime = models.ForeignKey(EventTime, null=True, on_delete=models.CASCADE)

appointment/forms.py
import models
from django import forms
from django.forms import SelectDateWidget
from appointment.models import Event, EventTime, Participants, EventDate
from crispy_forms.helper import FormHelper


class EventForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })
    class Meta():
        model = Event
        fields = ('title', 'description',)

class ParticipateForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        event = kwargs.pop('event', None)
        self.helper = FormHelper()
        super(ParticipateForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })
        if event:
            self.fields['eventDate']=forms.ModelChoiceField(queryset=EventDate.objects.filter(event=event),
                                                            widget = forms.RadioSelect())
            self.fields['eventTime'] = forms.ModelChoiceField(queryset=EventTime.objects.filter(eventDate=EventDate.objects.filter(event=event)),
                                                             widget=forms.RadioSelect())
    class Meta():
        model = Participants
        fields=('name', 'email')

class EventDateForm(forms.ModelForm):
    class Meta():
        model = EventDate
        fields = ('eventDate', )

    def __init__(self, event, *args, **kwargs):
        super(EventDateForm, self).__init__(*args, **kwargs)
        self.fields['eventDate'].queryset = EventDate.objects.filter(event=event)
        self.files['eventDate'].widget = forms.RadioSelect()

class EventTimeForm(forms.ModelForm):
    class Meta():
        model = EventTime
        fields = ('eventTimeStart',)

class ParticipantForm(forms.Form):
    class Meta():
        model = Participants
        fields = ('name', 'email')

class AddDayForm(forms.ModelForm):
    class Meta():
        model = EventTime
        fields = ('eventTimeStart', 'eventTimeFinish')
    eventDate = forms.DateField(widget=SelectDateWidget)

appointment/views.py
import simplejson

from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from appointment.forms import EventForm, AddDayForm, ParticipateForm
from appointment.models import Event, EventTime, EventDate, Participants


def appointent_list(request):
    events = Event.objects.all()
    context = {
        "events": events,
    }
    return render(request, 'appointment/events.html', context)

@csrf_exempt
def get_event_time(request, id):
    eventDate = EventDate.objects.get(id=id)
    eventTime = EventTime.objects.filter(eventDate=eventDate)
    time_dict = {}
    for time in eventTime:
        time_dict[time.id] = time.__str__()
    return HttpResponse(simplejson.dumps(time_dict))

@csrf_exempt
def get_event_part(request, id):
    participants = Participants.objects.filter(eventTime=id)
    part_dict = {}
    for part in participants:
        part_dict[part.name] = part.email
    return HttpResponse(simplejson.dumps(part_dict))

def appointment_detail(request, id):
    event = get_object_or_404(Event, id=id)
    form = ParticipateForm(event=event.id)
    context = {
        "event" : event,
        "form": form,
    }
    return render(request, 'appointment/eventDetail.html', context)

@transaction.atomic
def add_participant (request, id):
    event = get_object_or_404(Event, id=id)
    if request.method == 'POST':
        form = ParticipateForm(request.POST, event=event.id)
        if form.is_valid():
            eventDate = form.cleaned_data['eventDate']
            eventTime = form.cleaned_data['eventTime']
            if request.user.is_authenticated:
                name = request.user.username
                email = request.user.email
            else:
                name = form.cleaned_data['name']
                email = form.cleaned_data['email']
            participant = Participants(eventTime=eventTime, name=name, email=email)
            participant.save()

            part = Participants.objects.filter(eventTime=eventTime)
            context = {
                "form" : form,
                "event" : event,
                "part" : part,
            }
            return render(request, 'appointment/eventDetail.html', context)
        else:

            context = {"form" : form,
                       "event" : event,
                       }
            return render(request, 'appointment/eventDetail.html', context)

@login_required
@transaction.atomic
def add_event (request):
    form = EventForm()
    context = {
        "form": form,
    }
    return render(request, 'appointment/eventForm.html', context)

@login_required
@transaction.atomic
def save_event (request):
    if request.method == 'POST':
        form = EventForm(request.POST, instance=request.user)
        if form.is_valid():
            title = form.cleaned_data['title']
            description = form.cleaned_data['description']
            starter = request.user

            event = Event(title=title, description=description, starter=starter)
            event.save()
            return redirect('event-detail', event.id)
        else:
            form = EventForm()
            context = {"form" : form}
            return render(request, 'appointment/eventForm.html', context)

@login_required
@transaction.atomic
def event_add_day(request, id):
    event = get_object_or_404(Event, id=id)
    form = AddDayForm()
    context = {
        "form": form,
        "event": event,
    }
    return render(request, 'appointment/eventAddDay.html', context)

@login_required
@transaction.atomic
def event_save_day(request, id):
    if request.method == 'POST':
        form = AddDayForm(request.POST, instance=request.user)
        event = get_object_or_404(Event, id=id)

        if form.is_valid():
            eventDate = form.cleaned_data['eventDate']
            eventTimeStart = form.cleaned_data['eventTimeStart']
            eventTimeFinish = form.cleaned_data['eventTimeFinish']

            try:
                eventDateInst=EventDate.objects.get(event=event, eventDate=eventDate)
            except:
                eventDateInst = EventDate(eventDate=eventDate, event=event)
                eventDateInst.save()
            finally:
                eventTimeInst = EventTime(eventTimeStart = eventTimeStart,
                                          eventTimeFinish=eventTimeFinish, eventDate=eventDateInst)
                eventTimeInst.save()
            return redirect('event-detail', event.id)
        else:
            return redirect('event-add-day', event.id)

appointment/templates/appointment/eventAddDay.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    Add Event Day
{% endblock %}

{% block content %}

    <form action="{% url 'event-save-day' event.id %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
        <div class='form-group'>
            <input type="submit" class="button" value="Add Event Day">
        </div>
    </form>

{% endblock %}

appointment/templates/appointment/eventDetail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    Participate Event
{% endblock %}

{% block content %}

    <p>Event name: {{ event.title }}</p>
    <p>Event starter: {{ event.starter }}</p>
    <p>Event description: {{ event.description }}</p>

    <form id='event_form' name='event_form' action="{% url 'add-participant' event.id %}" method="POST" role="form">
    {% csrf_token %}
       {{ form }}
        <div class='form-group'>
            <input class='btn btn-default' type="submit" class="button" value="Participate">
        </div>
    </form>

    {% if user.is_authenticated %}
        <div class='form-group'>
            <a class='btn btn-default' href="{% url 'event-add-day' event.id %}">Add new Time</a>
        </div>
    {% endif %}

    {% if part %}
        <h4>Participants list:</h4>
        <table>
    <tr>
        <th>Name</th>
        <th>Email</th>
    </tr>
    {% for item in part %}
    <tr>
        <td> {{ item.name }} </td>
        <td> {{ item.email }} </td>
        </tr>
    {% endfor %}
    {% endif %}

    {% endblock %}
{% block javascript %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <script type="text/javascript">
      $(document).ready(function(){
          $('input[type=radio][name=eventDate]').change(function(){
        eventDate_id = $(this).val();
        request_url = '/appointment/get_event_time/' + eventDate_id + '/';
        $.ajax({
            url: request_url,
            success: function(data){
                var obj = JSON.parse(data);

                $('#id_eventTime').html("");
                for(var key in obj){
                   if (obj.hasOwnProperty(key)){
                       var value=obj[key];
                       var rdb = "<div class='radio'><label><input id='id_eventTime_" + key + "'" + "name='eventTime' type='radio' value='" + key + "'" + " />" + value + "</label></div>";
                       $('#id_eventTime').append(rdb);
                    }
                }
            }

        });
    })

    });
</script>
{% endblock %}

appointment/templates/appointment/eventForm.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    Create Event
{% endblock %}

{% block content %}

    <form action="{% url 'event-save' %}" method="POST">
    {% csrf_token %}
    {{ form }}

        <div class='form-group'>
            <input type="submit" class="button" value="Create Event">
        </div>
    </form>

{% endblock %}

appointment/templates/appointment/events.html
{% extends 'base.html' %}

{% block title %}
    Event list
{% endblock %}

{% block content %}

    <h1> Event List:</h1>
    {% for event in events %}
        <h4><a href="{% url 'event-detail' event.id %}"> "{{ event.title }}".  Starter : {{ event.starter }}</a></h4>
        <p> {{ event.get_cut }}</p>
      {% endfor %}
    {% if user.is_authenticated %}
        <a class='btn btn-default' href="{% url 'event-add' %}">Create Event</a>
    {% endif %}
{% endblock %}

appointment/templates/appointment/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
{% endblock %}